version: '2'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    restart: always
    build:
      context: pipeline
    ports:
      - "1010:8080"
    volumes:
      - "/var/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Africa/Johannesburg"
    networks:
      - net_pr

networks:
  net_pr:

